name: Build registry latest releases(20 tags)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  get-tags:
    runs-on: self-hosted
    outputs:
      tags: ${{ steps.set-tags.outputs.tags }}
    steps:
      - id: set-tags
        run: |
          TAGS=$(curl -s https://api.github.com/repos/distribution/distribution/releases | jq -r '.[].tag_name' | grep -E '^v[0-9]' | head -n 20 | jq -R . | jq -cs .)
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"
          

  build-image:
    needs: get-tags
    runs-on: self-hosted
    strategy:
      matrix:
        tag: ${{ fromJson(needs.get-tags.outputs.tags) }}
    env:
      DOCKER_VERSION: ${{ matrix.tag }}
    steps:

      - name: Clone Repo
        run: |
          git clone --depth 1 -b ${{ matrix.tag }} https://github.com/distribution/distribution src
          
      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: lcr.loongnix.cn
          
      - name: Build Image
        run: |
          cd src && python ../scripts/modify.py Dockerfile > Dockerfile && docker buildx build -t lcr.loongnix.cn/library/registry:${{ matrix.tag }} --push .
          
      - name: Clean cache
        run: |
          rm -rf src
      
